title: ROSを使用した画像処理とマニピュレータ制御
description: 日本ロボット学会　第121回 ロボットの作り方セミナー
theme: jekyll-theme-minimal

repo: "https://github.com/takahasi/ros_moveit_rsj_tutorial"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - README.md
  - Gemfile
